repos:
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v3.0.3
      hooks:
          - id: prettier
            language: node
            additional_dependencies:
                - prettier@^3.0.3
                - prettier-plugin-tailwindcss@^0.7.0
                - '@trivago/prettier-plugin-sort-imports@^6.0.0'

    - repo: https://github.com/pre-commit/mirrors-eslint
      rev: v9.15.0
      hooks:
          - id: eslint
            language: node
            additional_dependencies:
                - '@eslint/js@^9.15.0'
                - '@next/eslint-plugin-next@^16.0.0'
                - eslint@^9.15.0
                - eslint-import-resolver-typescript@^4.0.0
                - eslint-plugin-import@^2.31.0
                - eslint-plugin-jsx-a11y@^6.10.2
                - eslint-plugin-react@^7.37.2
                - eslint-plugin-react-hooks@^7.0.0
                - typescript-eslint@^8.16.0
