repos:
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v3.0.3
      hooks:
          - id: prettier
            additional_dependencies:
                - prettier@^3.0.3
                - prettier-plugin-tailwindcss@^0.5.3
                - '@trivago/prettier-plugin-sort-imports@^4.2.0'
    - repo: https://github.com/pre-commit/mirrors-eslint
      rev: v8.49.0
      hooks:
          - id: eslint
            additional_dependencies:
                - eslint@^8.49.0
                - eslint-config-next@^13.4.19
                - '@typescript-eslint/eslint-plugin@^6.7.0'
                - '@typescript-eslint/parser@^6.7.0'
