services:
    postgresql:
        image: postgres
        restart: unless-stopped
        ports:
            - '25432:5432'
        volumes:
            - postgresql-data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: nsflexinsights
            POSTGRES_PASSWORD: nsflexinsights
            POSTGRES_DB: nsflexinsights

volumes:
    postgresql-data:
