services:
    postgresql:
        image: postgres
        restart: unless-stopped
        ports:
            - '15432:5432'
        environment:
            POSTGRES_USER: nsflexinsights
            POSTGRES_PASSWORD: nsflexinsights
            POSTGRES_DB: nsflexinsights
